# Generated by Django 3.1 on 2020-08-13 22:27

import core.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissao_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('profissao_cliente', models.CharField(max_length=100, verbose_name='Profissão_Cliente')),
            ],
            options={
                'verbose_name': 'Profissão_Cliente',
                'verbose_name_plural': 'Profissões_Cliente',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('dep', models.TextField(max_length=200, verbose_name='Depoimento')),
                ('imagem', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem')),
                ('icone', models.CharField(choices=[('lni-star-filled', 'Estrela Preenchida'), ('lni-star-half', 'Meia estrela')], max_length=15, verbose_name='Icone')),
                ('profissao_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profissao_cliente', verbose_name='Profissão_Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
