# Generated by Django 3.1 on 2022-02-16 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_profissao_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='profissao_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.profissao_cliente', verbose_name='Profissão_Cliente'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='core.cargo', verbose_name='Cargo'),
        ),
    ]
